azurerm_mainrg                             = "rg-jodiesite-scus"
azurerm_mainlocation                       = "southcentralus"
azurerm_jodiesitename                      = "jodiesiteswa"
azurerm_jodiesitecosmosdbname              = "cosmos-jodiesitecounter-97e3ca8d"
azurerm_jodiesitecosmostablename           = "visitors"
